name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest ./order-service
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service:latest ./product-service
          docker push ${{ secrets.DOCKER_USERNAME }}/product-service:latest
          docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-service:latest ./payment-service
          docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:latest